import os
import json
import pickle
import argparse
from . import context
from shared.storage import ObjStr
from . import cleaning, restructuring, parsing, analysis

# Instantiates connection to storage
rpslyzer_output_path = os.getenv("DATA_INPUT_PATH")
objects_path = os.getenv("DATA_OUTPUT_PATH")

if not os.path.isdir(objects_path):
    os.mkdir(objects_path)
storage = ObjStr(objects_path)

# Parses command line arguments
parser = argparse.ArgumentParser(
    prog="rpslweb data processor",
    description="Processes further the data generated by RPSLyzer",
    epilog="For use with rpslweb's backend",
)
parser.add_argument("-o", "--organize", action="store_true")
parser.add_argument("-r", "--restructure", action="store_true")
parser.add_argument("-c", "--clean", action="store_true")
parser.add_argument("-p", "--parse", action="store_true")
parser.add_argument("-x", "--preprocess", action="store_true")
parser.add_argument("-a", "--analyze", action="store_true")
parser.add_argument("-f", "--full", action="store_true")
args = parser.parse_args()


# Organizes the raw output of rpslyzer
def organize():
    print("\n***STARTING ORGANIZATION***\n")

    # Unites the output from rpslyzer
    print("Uniting RPSLyzer's output...", end="", flush=True)
    files = os.listdir(rpslyzer_output_path)
    input_file = open(f"{rpslyzer_output_path}/{files[0]}")
    united = json.load(input_file)
    input_file.close()
    for i in range(1, len(files)):
        input_file = open(f"{rpslyzer_output_path}/{files[i]}")
        data = json.load(input_file)
        for key in united.keys():
            united[key] = united[key] | data[key]
        input_file.close()
    output_file = open(f"{rpslyzer_output_path}/full.json", "w")
    json.dump(united, output_file)
    output_file.close()
    print("DONE")

    # Converts every entry of the data to string
    print("Converting all data to strings...", end="", flush=True)
    f = open(f"{rpslyzer_output_path}/full.json")
    data = json.load(
        f,
        parse_float=lambda x: str(x),
        parse_int=lambda x: str(x),
        parse_constant=lambda x: str(x),
    )
    print("DONE")

    print("Writing to disk...", end="", flush=True)
    if not os.path.isdir(f"{objects_path}/raw"):
        os.mkdir(f"{objects_path}/raw")
    for key in data.keys():
        with open(f"{objects_path}/raw/{key}", "wb") as f:
            pickle.dump(data[key], f)
    f.close()
    print("DONE")

    print("\n***FINISHING ORGANIZATION***\n")


# Function for restructuring rpslyzers output
def restructure():
    print("\n***STARTING RESTRUCTURING***\n")

    # Opens the data
    print("Reading data...", end="", flush=True)
    data = storage.get_bucket("raw")
    print("DONE")

    # Calls the restructure module
    # Inplace modifications on data
    print("Restructuring data...", end="", flush=True)
    restructuring.process(data)
    print("DONE")

    # Writes back the cleaned data
    print("Writing to disk...", end="", flush=True)
    storage.set_bucket("preprocessed", data)
    print("DONE")

    print("\n***FINISHING RESTRUCTURING***\n")


# Function for cleaning the restructured data
def clean():
    print("\n***STARTING CLEANING***\n")

    # Opens the data
    print("Reading data...", end="", flush=True)
    data = storage.get_bucket("preprocessed")
    print("DONE")

    # Calls the cleaning module
    # Inplace modifications on data
    print("Cleaning data...", end="", flush=True)
    cleaning.process(data)
    print("DONE")

    # Writes back the cleaned data
    print("Writing to disk...", end="", flush=True)
    storage.set_bucket("preprocessed", data)
    print("DONE")

    print("\n***FINISHING CLEANING***\n")


# Function for parsing rpslyzers output
def parse():
    # Reads the output from RPSLyzer
    # Converts all numeric data types to string
    print("\n***STARTING PARSING***\n")
    print("Reading input data...", end="", flush=True)
    data = storage.get_bucket("preprocessed")
    print("DONE")

    # Processes each key of RPSLyzer's output
    rpslyzer_keys = [
        "aut_nums",
        "as_sets",
        "route_sets",
        "peering_sets",
        "filter_sets",
        "as_routes",
    ]
    for key in rpslyzer_keys:
        print(f"Processing '{key}'...", end="", flush=True)
        parsing.process(key, data[key], storage)
        print("DONE")

    print("\n***FINISHING PARSING***\n")
    del data


# Function for generating more data on top of RPSLyzer
def analyze():
    print("\n***STARTING ANALYSIS***\n")  # Analysis logging is done within the module

    # Processes the 'aut_nums' key
    analysis.process_relationships(storage)

    print("\n***FINISHING ANALYSIS***\n")


# Executes actions based on arguments
if args.full:
    organize()
    restructure()
    clean()
    parse()
    analyze()
    quit()
if args.preprocess:
    restructure()
    clean()
    parse()
    quit()
if args.organize:
    organize()
if args.restructure:
    restructure()
if args.clean:
    clean()
if args.parse:
    parse()
if args.analyze:
    analyze()
